---
title: "Photosynthetically Active Radiation"
author: "Benoît D'ANGELO"
date: "06/05/2015"
output:
  html_document:
  includes:
  in_header: ../../in_header.html
theme: flatly
---
  
<h3><a href="../../vis_toc.html"> Visualisation </a></h3>
***

```{r setup}
rm(list=ls(all=TRUE))

library(laguettevarspa)
library(snoweather)
library(bdphdtoolbox)

library(data.table)
library(dplyr)
library(tidyr)
library(ggplot2)

savpth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/data_treatment"
```

```{r load data}
# Fichier VS -- Données ponctuelles
df_p <- svCtrlFact %>%
  select(ID_camp, placette, date, NEE_time, PAR_Deb, PAR_Fin)%>%
  mutate(p_ts=as.POSIXct(paste(date, NEE_time, sep=" "), format="%Y-%m-%d %H:%M"))%>%
  group_by(p_ts)%>%
  mutate(PAR = mean(c(PAR_Deb, PAR_Fin), na.rm=T))%>%
  ungroup()

## Données météo, données continues
df_c <- wrLGT %>%
  select(timestamp, Rad_kW, Rad_MJ)%>%
  filter(timestamp >= as.POSIXct("01/03/2013", format = "%d/%m/%Y"))

# Keys
# ## valeur numérique 
# df_p <- data.table(df_p, key = "key_p")
# df_c <- data.table(df_c, key = "key_c")
## vs directement POSIXct
df_p <- data.table(df_p, key = "p_ts")
df_c <- data.table(df_c, key = "timestamp")

df <- df_c[df_p, roll="nearest"]
```


```{r}
ggplot(df, aes(x = Rad_kW, y = PAR))+
  geom_point()+
  theme_bw()

m <- lm(df$PAR~df$Rad_kW)
m0 <- lm(df$PAR~-1*df$Rad_kW)
summary(m)
plot(df$PAR~df$Rad_kW)
abline(m, col="blue")
abline(m0, col="red")


# 
# tt <- filter(df, placette == "p04")
# m0 <- lm(tt$PAR~-1+tt$Rad_kW)
# summary(m)
# summary(m0)
# plot(tt$PAR~tt$Rad_kW)
# abline(m, col="blue")
# abline(m0, col="red")

mdl <- df %>%
  group_by(placette)%>%
  do(lm_get_std(lm(.$PAR~.$Rad_kW)))%>%
  ungroup()%>%
  arrange(aR2)%>%
  mutate(pval_star=tc_pval(pval))
```

```{r}
# Calculate continuous profile temperature
result <- data.frame()
for(i in 1:NROW(mdl)){
# for(i in 1:200){ # les 30 premiers cm
  temp <- df_c
  temp$pred <- mdl$intercept[i] + mdl$slope[i]*temp$Rad_kW
  temp$placette <- mdl$placette[i]
  result <- rbind(result, temp)
}

cPAR <- result %>%
  select(timestamp, placette, pred)%>%
  rename(PAR=pred)
  
write.csv(cPAR, "../../../data/processed/cPAR.csv", row.names=FALSE, quote=FALSE)
write.csv(mdl, "../../../data/processed/cPAR_par.csv", row.names=FALSE, quote=FALSE)

plot(df$Rad_kW~df$Rad_MJ)
```
