---
title: "Photosynthetically Active Radiation"
author: "Benoît D'ANGELO"
date: "06/05/2015"
output:
  html_document:
  includes:
  in_header: ../../in_header.html
theme: flatly
---
  
<h3><a href="../../vis_toc.html"> Visualisation </a></h3>
***

```{r setup}
rm(list=ls(all=TRUE))

library(laguettevarspa)
library(snoweather)
library(bdphdtoolbox)

library(data.table)
library(xts)
library(dplyr)
library(tidyr)
library(ggplot2)

savpth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/data_treatment/pdata_to_cdata"
```

```{r load data}
# Fichier VS -- Données ponctuelles
## ctrl fact
dfctrl <- svCtrlFact %>%
  select(ID_camp, placette, date, NEE_time)
  # mutate(p_ts=as.POSIXct(paste(date, NEE_time, sep=" "), format="%Y-%m-%d %H:%M"))

## Vegetation
dfveg <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/svIVcov.csv") %>%
  select(ID_camp, placette, IVcov, IVcov_area, A, H, M)

df_p <- dfctrl %>%
  left_join(., dfveg, by=c("ID_camp", "placette"))

df_pm <- df_p %>%
  select(ID_camp, date, A, H, M, IVcov)%>%
  group_by(ID_camp)%>%
  summarise(date = min(date, na.rm=T),
            A=mean(A, na.rm=T), H=mean(H, na.rm=T), 
            M=mean(M, na.rm=T), IVcov=mean(IVcov, na.rm=T))%>%
  mutate(p_ts = as.POSIXct(as.character(date), format="%Y-%m-%d"))%>%
  select(-ID_camp, -date)

df_pm <- as.data.frame(df_pm)
#add line to force Herbacée at 0 at the start (during winter)
newrow <- data.frame(A=NA, H=0, M=NA, IVcov=c(0.15,0.2), p_ts=c(as.POSIXct("2013-01-01"),     as.POSIXct("2013-12-01")))

df_pm <- rbind(newrow, df_pm)

df_pm <- arrange(df_pm, p_ts)

# df_pm$timestamp <- as.POSIXct(df_pm$timestamp)

# df_p$p_ts <- as.POSIXct(round(df_p$p_ts, "hours"))
# df_pm$p_ts <- as.POSIXct(round(df_pm$p_ts, "hours"))


## Données météo, données continues
df_c <- wrLGT %>%
  select(timestamp, Ta)%>%
  filter(timestamp >= as.POSIXct("01/01/2013", format = "%d/%m/%Y"))%>%
  mutate(day = cut(timestamp, breaks="days"))%>% # daily mean
  select(-timestamp)%>%
  group_by(day)%>%
  summarise_each(funs(mean))%>%
  mutate(timestamp = as.POSIXct(day, format="%Y-%m-%d"))%>%
  select(-day)


xdf_c <- xts(df_c$Ta, order.by = df_c$timestamp)

xdf_pm_H <- xts(df_pm$H, order.by = df_pm$p_ts)
xdf_pm_IVcov <- xts(df_pm$IVcov, order.by = df_pm$p_ts)
# xdf_pm <- xts(df_pm[,c(3:5)], order.by = df_pm$p_ts)

# data.table
# df_pm <- data.table(df_pm, key = "p_ts")
# df_c <- data.table(df_c, key = "timestamp")
# df <- df_pm[df_c,]

# xts
df1 <- merge(xdf_c, xdf_pm_H)
df2 <- merge(xdf_c, xdf_pm_IVcov)
# interpol
df1$xdf_pmc_H <- na.approx(df1$xdf_pm_H)
df2$xdf_pmc_IVcov <- na.approx(df2$xdf_pm_IVcov)

df <- merge(df1,df2)

plot(df$xdf_pmc_IVcov)
points(df$xdf_pm_IVcov)

t <- as.data.frame(df)
tt <- data.frame(timestamp=rownames(t), t, row.names = NULL)

cVegm <- tt %>%
  select(timestamp, xdf_pmc_H, xdf_pmc_IVcov)%>%
  rename(H = xdf_pmc_H, IVcov = xdf_pmc_IVcov)
  

write.csv(cVegm, "../../../data/processed/pdata_to_cdata/cVeg_all_day.csv", row.names=FALSE, quote=FALSE)
```


```{r, eval=F}
# ggplot(df, aes(x = Rad_kW, y = PAR))+
#   geom_point()+
#   theme_bw()
# 
# m <- lm(df$PAR~df$Rad_kW)
# m0 <- lm(df$PAR~-1*df$Rad_kW)
# summary(m)
# plot(df$PAR~df$Rad_kW)
# abline(m, col="blue")
# abline(m0, col="red")


# 
# tt <- filter(df, placette == "p04")
# m0 <- lm(tt$PAR~-1+tt$Rad_kW)
# summary(m)
# summary(m0)
# plot(tt$PAR~tt$Rad_kW)
# abline(m, col="blue")
# abline(m0, col="red")

mdl_p7 <- df %>%
  group_by(placette)%>%
  do(lm_get_std(lm(.$PAR~.$Rad_kW)))%>%
  ungroup()%>%
  arrange(aR2)%>%
  mutate(pval_star=tc_pval(pval))
# For all placette
mdl_all <-lm_get_std(lm(df$PAR~df$Rad_kW)) %>%
  # ungroup()%>%
  # arrange(aR2)%>%
  mutate(pval_star=tc_pval(pval))
```

```{r, eval=F}
# Calculate continuous profile temperature
result_p7 <- data.frame()
for(i in 1:NROW(mdl_p7)){
# for(i in 1:200){ # les 30 premiers cm
  temp <- df_c
  temp$pred <- mdl_p7$intercept[i] + mdl_p7$slope[i]*temp$Rad_kW
  temp$placette <- mdl_p7$placette[i]
  result_p7 <- rbind(result_p7, temp)
}
cPAR_p7 <- result_p7 %>%
  select(timestamp, placette, pred)%>%
  rename(PAR=pred)

# For all p7 pooled
result_all <- df_c
result_all$pred <- mdl_all$intercept[1] + mdl_all$slope[1]*df_c$Rad_kW

cPAR_all <- result_all %>%
  select(timestamp, pred)%>%
  rename(PAR=pred)
```
  
```{r, eval=F}
# Export csv files
## per p7
write.csv(cPAR_p7, "../../../data/processed/pdata_to_cdata/cVeg_p7.csv", row.names=FALSE, quote=FALSE)
write.csv(mdl_p7, "../../../data/processed/pdata_to_cdata/cVeg_p7_par.csv", row.names=FALSE, quote=FALSE)
## For all p7 pooled
write.csv(cPAR_all, "../../../data/processed/pdata_to_cdata/cVeg_all.csv", row.names=FALSE, quote=FALSE)
write.csv(mdl_all, "../../../data/processed/pdata_to_cdata/cVeg_all_par.csv", row.names=FALSE, quote=FALSE)

plot(df$Rad_kW~df$Rad_MJ)
```
