---
title: "Gross Primary Production (GPP)"
author: "Benoît D'ANGELO"
date: "23/02/2015"
output:
  html_document:
    includes:
      in_header: ../../in_header.html
    theme: flatly
---

<h3><a href="../vis_toc.html"> Visualisation </a></h3>
  
***

```{r, echo=FALSE, message=FALSE}
rm(list=ls(all=TRUE))
library(laguettevarspa)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
savpth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/visualisation"

source("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/src/report/vis_plot.R")
# TODO
# units on axis

```


```{r load_data, echo=FALSE, message=FALSE}
df_ER <- svNetFlux %>%
  filter(type == "ER")%>%
  select(ID_camp, placette, netCO2F, timestamp)%>%
  rename(ER=netCO2F, ER_ts=timestamp)%>%
  mutate(ER_ts=as.POSIXct(ER_ts))

df_NEE <- svNetFlux %>%
  filter(type == "NEE") %>%
  select(ID_camp, placette, netCO2F, timestamp)%>%
  rename(NEE=netCO2F, NEE_ts=timestamp)%>%
  mutate(NEE_ts=as.POSIXct(NEE_ts))

df <- inner_join(df_ER, df_NEE)%>%
  mutate(netCO2F=NEE+ER) %>%
  group_by(ID_camp, placette)%>%
  mutate(timestamp=mean.POSIXct(c(ER_ts, NEE_ts)))%>%
  ungroup()%>%
  select(ID_camp, placette, netCO2F, timestamp)%>%
  # common with ER and NEE
  separate(timestamp, c("date", "time"), sep=" ") %>%
  separate(date, c("year","month", "day"),remove = F) %>%
  mutate(time = substr(time, 1, 5), ID_camp = as.factor(ID_camp), date=as.Date(date))

lab_Y <- expression(paste("PPB (", mu, mol,m^-2,s^-1,")", sep=""))

mdf <- df %>%
  group_by(ID_camp)%>%
  summarise(netCO2F_sd=sd(netCO2F),netCO2F=mean(netCO2F), date=mean(date))
```

## GPP measurements across field campaign
```{r, echo=FALSE, fig.width=9}
# Observation number
nobs <- paste("N :", as.character(NROW(df)))

flplt(df, lab_Y) # /src/report/vis_plot
ggsave("GPP_evolution.pdf", path=savpth)

ggplot(mdf, aes(x=date, y=netCO2F))+
  geom_point(size=3)+
  geom_linerange(aes(x=date, ymin=netCO2F-netCO2F_sd, ymax=netCO2F+netCO2F_sd))+
  labs(y=lab_Y, x="2013-2014")+
  scale_x_date(breaks = date_breaks("2 months"), labels = date_format("%b"))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank(), # DIAPO
        panel.grid.major.y = element_line(size=.05, colour="gray95"), # DIAPO
        panel.grid.minor = element_blank()) # DIAPO)
ggsave("GPP_evolution_avg.pdf", path=savpth, width=7, height=3)

```

## Annual mean differences significance:

```{r}
A <- filter(df, year==2013)
B <- filter(df, year==2014)
t.test(A$netCO2F, B$netCO2F)
```

## Normality test:

The normality tests (for NEE and ER) are available [here](flux_norm_test.html)

## Individual plot measurements

```{r, echo=FALSE, fig.width=10, fig.height=6}
p7_fl_plt(df, lab_Y)
ggsave("GPP_p7_evolution.pdf", path=savpth)
```

## Annual mean and standard deviation
```{r, echo=FALSE}
df %>%
  group_by(year) %>%
  summarise(GPP = round(mean(netCO2F, na.rm=T),2), GPP_sd = round(sd(netCO2F, na.rm=T),2))
```

## Montly GPP means per year

```{r, echo=FALSE}
ann_month_mean_fl(df, lab_Y)
```

## Montly GPP mean (pooling all years)

```{r, echo=FALSE}
month_mean_fl(df, lab_Y)
```
