---
title: "Calibration ch4 (moy/campagne)"
author: "Benoît D'ANGELO"
date: "14 avril 2016"
output:
  html_document:
    code_folding: hide
    fig_height: 3
    fig_width: 7
    includes:
      in_header: ../../in_header.html
    theme: flatly
    toc: yes
    toc_depth: 2
    toc_float: true
---

<h3><a href="../mod_toc.html"> Calibration </a></h3>
***

# Objectives
This files describe the calibration of the CH4 fluxes. One file is generated:

* CH4_mdlpar.csv (contains models parameters)

# Setup

## Load packages and set paths

```{r ld_pckg, message=FALSE}
# File name : /2013_spavar_LG/report/visualisation/flux/methane.Rmd
rm(list=ls(all=TRUE)) # Clean start

# Homemade packages (see "Howto" page to install them)
library(bdphdtoolbox)     # personnal toolbox

# CRAN packages
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(scales)

# Folder to save graphes
savpth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/visualisation"

# Folder to save data treatement
outpth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed"

# allow wider tables and graphes in html output
options(width = 100)

# Load custom color set
source("../../../src/report/custom_colors.R")
# source("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/src/report/custom_colors.R")
```

## Load functions

```{r ld_fn}
mdl_exp <- function(df, strt=list(a=0.1, b=0.3)){
mdl <- nls(Y ~ a * exp(b*X), data=df, start=strt, na.action = na.exclude)
}
mdl_lin <- function(df){
mdl <- nls(Y ~ a + b*X, data=df, start=list(a=0.1, b=0.3), na.action = na.exclude)
}

mdl_param <- function(df, mdl){
  # R2
  devmean <- df$Y-(mean(df$Y)) # deviation à la moyenne
  SSres <-sum((resid(mdl))^2) # Total sum of squares
  SStot <- sum(devmean^2) # Residual sum of squares
  # 2 way to calculate
  # R2 <- (SStot-SSres)/SStot 
  R2 <- 1 - SSres/SStot
  # Adjusted R2
  N <- NROW(devmean) # sample size
  p <- 1 # number of predictors
  R2a <- 1-((1-R2)*(N-1))/(N-p-1)
  # RMSE
  rmse_mdl <- sqrt(mean(((predict(mdl))-df$Y)^2,na.rm=TRUE))
  nrmse_mdl <- 100*rmse_mdl/mean(df$Y)
  # Collect usefull param
  df <- data.frame(a=coef(mdl)[1],
                   b=coef(mdl)[2],
                   c=coef(mdl)[3],
                   a_se=coef(summary(mdl))[,"Std. Error"][1],
                   b_se=coef(summary(mdl))[,"Std. Error"][2],
                   c_se=coef(summary(mdl))[,"Std. Error"][3],
                   a_pval=coef(summary(mdl))[,"Pr(>|t|)"][1],
                   b_pval=coef(summary(mdl))[,"Pr(>|t|)"][2],
                   c_pval=coef(summary(mdl))[,"Pr(>|t|)"][3],
                   R2=R2,
                   aR2=R2a,
                   rmse=rmse_mdl,
                   nrmse=nrmse_mdl,
                   aic=AIC(mdl),
                   bic=BIC(mdl))
  return(df)
}

pmesmod <- function(df, mdl){
par(mar=c(4,4.5,.5,.5))
plot(Y~predict(mdl), 
     # ylim=c(0,200),xlim=c(0,200),
     xlab="", ylab="", data=df)
     # xlab=expression(paste("CH"[4]," modélisée (", mu, mol,m^-2,s^-1,")", sep="")),
     
     # ylab=expression(paste("CH"[4]," mesurée (", mu, mol,m^-2,s^-1,")", sep="")), data=df)
title(xlab=expression(paste("CH"[4]," modélisée (", mu, mol,m^-2,s^-1,")", sep="")), line=2.5)
title(ylab=expression(paste("CH"[4]," mesurée (", mu, mol,m^-2,s^-1,")", sep="")), line=2)
abline(a=0, b=1, col="black", lty=2)
text(.16,.17, "1:1", srt=45)
}
```


## Load and transform data

```{r ld_data}
# Load treated data (generated with getClean_fluxesFC)
df <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/cl_fluxesFC.csv")%>%
  mutate(timestamp=as.POSIXct(as.character(timestamp)))%>%
  mutate(date=as.POSIXct(as.character(date)))

# Load treated data (generated with getClean_fluxesFC)
dfm <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/cl_fluxesFC_avg.csv")%>%
  mutate(timestamp=as.POSIXct(as.character(timestamp)))%>%
  mutate(date=as.POSIXct(as.character(date)))
```

# Calculations
```{r mdl_calc}
# tt <- dfm %>%
#   mutate(Y=CH4, X=WTL)
# 
# t <- nls(Y ~ a*X*exp(-b*X), data=tt, start=list(a=9,b=1), na.action = na.exclude)
# summary(t)
# par <- mdl_param(tt, t)

# IVcov mdl exp
dmdl_IVcov <- dfm %>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=IVcov)%>%
  select(Y, X, WTL, Tair, A, H, M, T20, T30, T40, T50, T80)
mdl_IVcov_lin <- mdl_lin(dmdl_IVcov)
par_IVcov_lin <- mdl_param(dmdl_IVcov, mdl_IVcov_lin)

mdl_IVcov_exp <- mdl_exp(dmdl_IVcov, strt=list(a=.1, b=.2))
par_IVcov_exp <- mdl_param(dmdl_IVcov, mdl_IVcov_exp)

# T40 mdl exp
dmdl_T40 <- dfm %>%
  filter(!is.na(CH4))%>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=T40)%>%
  select(Y, X, WTL, Tair, A, IVcov, M)
mdl_T40_lin <- mdl_lin(dmdl_T40)
par_T40_lin <- mdl_param(dmdl_T40, mdl_T40_lin)

mdl_T40_exp <- mdl_exp(dmdl_T40, strt=list(a=.1, b=0.01))
par_T40_exp <- mdl_param(dmdl_T40, mdl_T40_exp)

# T80 mdl exp
dmdl_T80 <- dfm %>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=T80)%>%
  select(Y, X, WTL, Tair, A, IVcov, M)
mdl_T80_lin <- mdl_lin(dmdl_T80)
par_T80_lin <- mdl_param(dmdl_T80, mdl_T80_lin)

mdl_T80_exp <- mdl_exp(dmdl_T80, strt=list(a=.1, b=0.01))
par_T80_exp <- mdl_param(dmdl_T80, mdl_T80_exp)

# H mdl exp
dmdl_H <- dfm %>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=H)%>%
  select(Y, X, WTL, Tair, A, IVcov, M, T20, T30, T40, T50, T80)
mdl_H_lin <- mdl_lin(dmdl_H)
par_H_lin <- mdl_param(dmdl_H, mdl_H_lin)

mdl_H_exp <- mdl_exp(dmdl_H, strt=list(a=.1, b=0.01))
par_H_exp <- mdl_param(dmdl_H, mdl_H_exp)

# A mdl exp
dmdl_A <- dfm %>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=A)%>%
  select(Y, X, WTL, Tair, M, H, IVcov)
mdl_A_lin <- mdl_lin(dmdl_A)
par_A_lin <- mdl_param(dmdl_A, mdl_A_lin)

mdl_A_exp <- mdl_exp(dmdl_A, strt=list(a=.1, b=0.01))
par_A_exp <- mdl_param(dmdl_A, mdl_A_exp)

```

```{r mdl_output}
# Resume
mdlls <- c("IVcov_lin", "IVcov_exp", "H_lin", "H_exp", "A_lin","A_exp", "T40_exp", "T80_exp")

par <- c(par_IVcov_lin, par_IVcov_exp,
         par_H_lin, par_H_exp,
         par_A_lin, par_A_lin,
         par_T40_exp, par_T80_exp)
mdlpar <- data.frame(matrix(unlist(par), nrow=length(mdlls), byrow=T))
colnames(mdlpar) <- c("a", "b", "c", "a_se", "b_se", "c_se", "a_pval", "b_pval", "c_pval", "R2", "R2a", "rmse", "nrmse", "aic", "bic")

res <- data.frame(mdl=mdlls)
res <- cbind(res, mdlpar)
result <- res
result[,-1] <- round(result[,-1],2) # round sauf 1re col

result %>%
  select(mdl, R2, R2a, rmse, nrmse, aic, bic)%>%
  arrange(desc(R2a))

result %>%
  select(mdl, a, b, c, a_se, b_se, c_se, a_pval, b_pval, c_pval)

ggplot(dfm, aes(y=CH4, x=H))+
  geom_point(size=3)+
  theme_bw()


ggplot(dfm, aes(y=CH4, x=IVcov))+
  geom_point(size=3)+
  theme_bw()
```



# Figures
```{r, fig.height=8}
labpar_1 <- format(par_IVcov_exp,  digits=2, nsmall=2)

lab11 <- paste(
  "y = ", labpar_1$a, " * exp(", labpar_1$b, "*Tair)",
  "\nR² = ", labpar_1$aR2, 
  "\nRMSE = ", labpar_1$rmse, 
  "\nNRMSE = ", labpar_1$nrmse, " %", sep="")



cairo_pdf(file.path("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/carbonbalance/ecosyst/CH4", "CH4_IVcov_mdl_mesmod.pdf"), width=9, height=8)
par(mfrow=c(2,2))

# haut
pmesmod(dmdl_IVcov, mdl_IVcov_exp)
text(x=2, y=172, labels=lab11, adj=0)
text(x=190, y=6, labels="a", adj=0, cex=2)

plot(resid(mdl_IVcov_exp)~predict(mdl_IVcov_exp), 
     xlab="", ylab="", ylim=c(-0.06, 0.06))
abline(h=0, lty="dashed")
abline(h=0.04, lty="dotted")
abline(h=-0.04, lty="dotted")
title(xlab=expression(paste("Valeurs prédites (", mu, mol,m^-2,s^-1,")", sep="")), line=2.5)
title(ylab=expression(paste("Résidus (", mu, mol,m^-2,s^-1,")", sep="")), line=2)
text(x=170, y=-35, labels="b", adj=0, cex=2)

## bas gauche
plot(resid(mdl_IVcov_exp)~dmdl_IVcov$WTL, xlab="", ylab="", ylim=c(-0.06, 0.06)) 
title(xlab="Niveau de la nappe (cm)", line=2.5)
title(ylab=expression(paste("Résidus (", mu, mol,m^-2,s^-1,")", sep="")), line=2)
text(x=11, y=-35, labels="c", adj=0, cex=2)
## bas droit
plot(resid(mdl_IVcov_exp)~dmdl_IVcov$T20, xlab="", ylab="", ylim=c(-0.06, 0.06)) 
title(xlab="Température du sol à -20 cm (°C)", line=2.5)
title(ylab=expression(paste("Résidus (", mu, mol,m^-2,s^-1,")", sep="")), line=2)
text(x=34, y=-35, labels="d", adj=0, cex=2)

par(mfrow=c(1,1))
dev.off()




## Figure vis flux fact crtl
plt <- df %>%
  select(NEE, ER, GPP, CH4, IVcov, WTL, Tair)
# cairo_pdf(file.path("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/carbonbalance/ecosyst/CH4", "CH4_T5_mdl_res.pdf"), width=5, height=4)
par(mfrow=c(3,3), mar=c(1.5,4.5,.5,.5))
# Haut
plot(GPP~Tair, 
     data=plt,
     xlab="",
     ylab="")
title(ylab=expression(paste("PPB (", mu, mol,m^-2,s^-1,")", sep="")), line=2)
par(mar=c(1.5,1.6,.5,.5))
plot(GPP~IVcov, 
     data=plt,
     xlab="",
     ylab="")
plot(GPP~WTL, 
     data=plt,
     xlab="",
     ylab="")
# Milieu
par(mar=c(1.5,4.5,.5,.5))
plot(ER~Tair, 
     data=plt,
     xlab="",
     ylab="")
title(ylab=expression(paste("RE (", mu, mol,m^-2,s^-1,")", sep="")), line=2)
par(mar=c(1.5,1.6,.5,.5))
plot(ER~IVcov, 
     data=plt,
     xlab="",
     ylab="")
plot(ER~WTL, 
     data=plt,
     xlab="",
     ylab="")

# Bas
par(mar=c(4,4.5,.5,.5))
plot(CH4~Tair, 
     data=plt,
     xlab="",
     ylab="")
title(ylab=expression(paste("CH4 (", nmol,m^-2,s^-1,")", sep="")), line=2)
title(xlab="Température de l'air (°C)", line=2.5)
par(mar=c(4,1.6,.5,.5))
plot(CH4~IVcov, 
     data=plt,
     xlab="",
     ylab="")
title(xlab="Indice de végétation", line=2.5)
plot(CH4~WTL, 
     data=plt,
     xlab="",
     ylab="")
title(xlab="Niveau de la nappe (cm)", line=2.5)

par(mfrow=c(1,1))
# dev.off()

# plt <- dfm %>%
#   select(NEE, ER, GPP, CH4, IVcov, WTL, Tair)

plt2 <- df %>%
  select(NEE, ER, GPP, CH4, IVcov, WTL, Tair)%>%
  rename(RE=ER, PPB=GPP, IV=IVcov, "Niveau nappe"=WTL)%>%
  gather("F_type", "F_val", 1:4)%>%
  gather("FC_type", "FC_val", 1:3)%>%
  filter(F_type != "NEE")

ggplot(plt2, aes(x = FC_val, y = F_val))+
  geom_point(size=3, shape=21)+
  facet_grid(F_type~FC_type, scales="free")+
  annotate("text", label=c("A","B","C","D","E","F","G","H","I"), x=+Inf, y=+Inf, hjust=2, vjust=2)+
  labs(x="Facteurs contrôlants", y=expression(paste("Flux (", mu, mol,m^-2,s^-1,")", sep="")))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.05, colour="gray95"),
        strip.background = element_blank(),
        panel.grid.minor = element_blank()) 
ggsave("Fl_FC.pdf", path=savpth, width=7, height=5)

```

```{r, eval=F}
t <- plt2 %>%
# filter(FC_type == "Niveau nappe", F_type == "PPB")%>%
# filter(FC_type == "Niveau nappe", F_type == "RE")%>%
# filter(FC_type == "Niveau nappe", F_type == "CH4")%>%
filter(FC_type == "Tair", F_type == "PPB")%>%
# filter(FC_type == "Tair", F_type == "RE")%>%
# filter(FC_type == "Tair", F_type == "CH4")%>%
# filter(FC_type == "IV", F_type == "PPB")%>%
# filter(FC_type == "IV", F_type == "RE")%>%
# filter(FC_type == "IV", F_type == "CH4")%>%
do(na.omit(.))

cor(t$F_val, t$FC_val)
plot(t$F_val~t$FC_val)
```

# Data
```{r sav_mdl_par}
export <- res %>%
  select(mdl, a, b, c)

write.csv(export, file.path(outpth, "/CH4_mdlpar.csv"), quote=F, row.names=F)
```

