---
title: "GPP models validation"
author: "Benoît D'ANGELO"
date: "07/04/2015"
output:
  html_document:
    code_folding: hide
    includes:
      in_header: ../../in_header.html
    theme: flatly
    toc: yes
    toc_depth: 2
    toc_float: true
---

<h3><a href="../mod_toc.html"> Modélisation </a></h3>

***

# Objectives
This files describe the validation of the GPP fluxes. 1 files are generated:

* GPP_pred_val.csv (contains models predictions)

# Setup

## Load packages and set paths

```{r setup, message=FALSE}
# filname: /2013_spavar_LG/report/modelisation/validation/GPP_perCampaign_val.Rmd
rm(list=ls(all=TRUE)) # Clean start
# Homemade
library(laguettevarspa)
library(carbiodiv)
library(snoweather)
library(bdphdtoolbox)

# CRAN
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(rprojroot)
## Find project root
r <- rprojroot::is_rstudio_project
root <- r$find_file()
## Folder to save the treatements
outpath <- file.path(root, "data", "processed")

options(width = 200)
```

## Load functions

```{r}
mdl_indic <- function(Y, pY, mdl){
  mdl <- unique(mdl)
  if(grepl("_", mdl)){
    p <- 2
  }else{ p <- 1}
  # R2
  devmean <- Y-(mean(Y, na.rm=TRUE)) # deviation à la moyenne
  SSres <-sum((Y-pY)^2) # Total sum of squares
  SStot <- sum(devmean^2) # Residual sum of squares
  # 2 way to calculate
  R2 <- (SStot-SSres)/SStot 
  # R2 <- 1 - SSres/SStot
  # Adjusted R2
  N <- NROW(devmean) # sample size
  # p <- 1 # number of predictors
  R2a <- 1-((1-R2)*(N-1))/(N-p-1)
  # RMSE
  rmse_mdl <- sqrt(mean((pY-Y)^2,na.rm=TRUE))
  nrmse_mdl <- 100*rmse_mdl/mean(Y,na.rm=TRUE)
  # Collect usefull param
  df <- data.frame(R2=R2,
                   aR2=R2a,
                   rmse=rmse_mdl,
                   nrmse=nrmse_mdl)
  return(df)
}

```

## Load data

```{r load_mdl_par}
GPPallpar <- read.csv(file.path(outpath, "GPPsatGPP_mdl_par.csv"))
GPPsatpar <- GPPallpar%>%
  select(-i)
GPPpar <- GPPallpar%>%
  select(mdl, i)
```

```{r load_data}
# Load treated data (generated with getClean_carbiodiv_val_data)
# Campaign average
dfm <- read.csv(file.path(outpath, "cl_carbiodiv_val.csv"))
```

# Calculations

```{r, compil_data}
mdl_list <- c("exp-Tair", "exp-T5", "exp-Tair_H", "exp-Tair_IVcov", "exp-T5_IVcov")

GPPpred <- data.frame()
for (j in mdl_list){
    # Setup
    # GPPsat calc
    dat <- prd_seldat(df=dfm, flux = "GPP", id_eq = j) # Select data
    par <- prd_gpar(id_eq = j, dfparam = GPPsatpar) # Select parameter
    colnames(dat) <- prd_prpdat(dat, resp_var = T)
    pGPPsat <- gpGPPsat(df=dat, p=par) # prep data and calc pred
    # GPP calc
    par_i <- prd_gpar(id_eq = j, dfparam = GPPpar) # Select parameter
    pGPP = (par_i*dfm$PAR*pGPPsat/(pGPPsat+dfm$PAR*par_i))
    # Output
    ## GPPsat
    tpGPPsat <- data.frame(GPP=dfm$GPP, mdl=j, pGPPsat=pGPPsat, pGPP=pGPP)
    GPPpred <- rbind(GPPpred,tpGPPsat) 
}
```

```{r}
# Tableau resultats modèles GPP
resGPP <- GPPpred %>%
  do(na.omit(.))%>%
  group_by(mdl)%>%
  do(mdl_indic(.$GPP, .$pGPP, mdl=.$mdl))%>%
  ungroup()%>%
  arrange(desc(aR2))
```

# Models validation {.tabset}

```{r}
resGPP
```

## Ta

```{r, fig.width=4, fig.height=4}
dat <- filter(GPPpred, mdl == "exp-Tair")
plt_mesmod(dat$GPP, dat$pGPP, x_lim = c(0,10), y_lim = c(0,10))
```

## T5

```{r, fig.width=4, fig.height=4}
dat <- filter(GPPpred, mdl == "exp-T5")
plt_mesmod(dat$GPP, dat$pGPP, x_lim = c(0,10), y_lim = c(0,10))
```

## Tair_H

```{r, fig.width=4, fig.height=4}
dat <- filter(GPPpred, mdl == "exp-Tair_H")
plt_mesmod(dat$GPP, dat$pGPP, x_lim = c(0,10), y_lim = c(0,10))
```


## Tair_IVcov

```{r, fig.width=4, fig.height=4}
dat <- filter(GPPpred, mdl == "exp-Tair_IVcov")
plt_mesmod(dat$GPP, dat$pGPP, x_lim = c(0,10), y_lim = c(0,10))
```

## T5_IVcov

```{r, fig.width=4, fig.height=4}
dat <- filter(GPPpred, mdl == "exp-T5_IVcov")
plt_mesmod(dat$GPP, dat$pGPP, x_lim = c(0,10), y_lim = c(0,10))
```

# Save
```{r}
write.csv(GPPpred, file.path(outpath, "GPP_pred_val.csv"), quote=F, row.names=F)
```


