---
title: "Méthane"
author: "Benoît D'ANGELO"
date: "21/07/2015"
output:
  html_document:
    fig_height: 3
    fig_width: 7
    includes:
      in_header: ../../in_header.html
    theme: flatly
---

<h3><a href="../vis_toc.html"> Visualisation </a></h3>
***

```{r, echo=FALSE, message=FALSE}
rm(list=ls(all=TRUE))

library(laguettevarspa)
library(snoweather)
library(carbiodiv)


library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(scales)

savpth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/visualisation"

outpth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed"

# TODO
# units on axis
opts_chunk$set(echo = F)
options(width = 100)

```

```{r}
panel.cor <- function(x, y, digits=2, prefix="", cex.cor)
     {
         usr <- par("usr"); on.exit(par(usr))
         par(usr = c(0, 1, 0, 1))
         r = (cor(x, y))
         txt <- format(c(r, 0.123456789), digits=digits)[1]
         txt <- paste(prefix, txt, sep="")
         if(missing(cex.cor)) cex <- 0.8/strwidth(txt)
         text(0.5, 0.5, txt, cex = cex * abs(r))
}


mdl_exp <- function(df, strt=list(a=0.1, b=0.3)){
mdl <- nls(Y ~ a * exp(b*X), data=df, start=strt, na.action = na.exclude)
}
mdl_lin <- function(df){
mdl <- nls(Y ~ a + b*X, data=df, start=list(a=0.1, b=0.3), na.action = na.exclude)
}

mdl_param <- function(df, mdl){
  # R2
  devmean <- df$Y-(mean(df$Y)) # deviation à la moyenne
  SSres <-sum((resid(mdl))^2) # Total sum of squares
  SStot <- sum(devmean^2) # Residual sum of squares
  # 2 way to calculate
  # R2 <- (SStot-SSres)/SStot 
  R2 <- 1 - SSres/SStot
  # Adjusted R2
  N <- NROW(devmean) # sample size
  p <- 1 # number of predictors
  R2a <- 1-((1-R2)*(N-1))/(N-p-1)
  # RMSE
  rmse_mdl <- sqrt(mean(((predict(mdl))-df$Y)^2,na.rm=TRUE))
  nrmse_mdl <- 100*rmse_mdl/mean(df$Y)
  # Collect usefull param
  df <- data.frame(a=coef(mdl)[1],
                   b=coef(mdl)[2],
                   c=coef(mdl)[3],
                   a_se=coef(summary(mdl))[,"Std. Error"][1],
                   b_se=coef(summary(mdl))[,"Std. Error"][2],
                   c_se=coef(summary(mdl))[,"Std. Error"][3],
                   R2=R2,
                   aR2=R2a,
                   rmse=rmse_mdl,
                   nrmse=nrmse_mdl,
                   aic=AIC(mdl),
                   bic=BIC(mdl))
  return(df)
}


pmesmod <- function(df, mdl){
par(mar=c(4,4.5,.5,.5))
plot(Y~predict(mdl), 
     # ylim=c(0,200),xlim=c(0,200),
     xlab="", ylab="", data=df)
     # xlab=expression(paste("CH"[4]," modélisée (", mu, mol,m^-2,s^-1,")", sep="")),
     
     # ylab=expression(paste("CH"[4]," mesurée (", mu, mol,m^-2,s^-1,")", sep="")), data=df)
title(xlab=expression(paste("CH"[4]," modélisée (", mu, mol,m^-2,s^-1,")", sep="")), line=2.5)
title(ylab=expression(paste("CH"[4]," mesurée (", mu, mol,m^-2,s^-1,")", sep="")), line=2)
abline(a=0, b=1, col="black", lty=2)
text(.16,.17, "1:1", srt=45)
}

presmod <- function(mdl){
par(mar=c(4,4,.5,.5))
plot(resid(mdl)~predict(mdl), xlab="valeurs prédites", ylab="résidus")
}
```


```{r , echo=FALSE}
df <- svCH4
# umol m-2 s-1

df$date <- as.Date(df$date, format="%Y-%m-%d")

all <- filter(df, 
              CH4 < 1, 
              plot != "ETREPEE")

lookup <- c("1" = "p01", "2" = "p02", "3" = "p03", "4" = "p04", "5" = "p05", "6" = "p06", "5'"="A", "5\""="B", "ETREPEE"="C")

#########################################################
# df avec données recouvrant la VS
vsch4 <- all %>%
  select(ID_camp_co2, date, time, plot, CH4)%>%
  filter(ID_camp_co2 != "none")%>% # retrait campagne méthane sans CO2
  filter(plot %in% c(1,2,3,4,5,6))%>% # retrait embases autre que VS
  mutate(plot = as.numeric(as.character(plot)))%>%
  mutate(placette = lookup[plot])%>%
  select(-plot)%>%
  mutate(time = as.character(time))%>%
  mutate(time = ifelse(is.na(time), "12:00:00", time))%>%
  mutate(ts_ch4 = paste(as.character(date), as.character(time)))%>%
  mutate(ts_ch4 = as.POSIXct(ts_ch4, format="%Y-%m-%d %H:%M:%S"))%>%
  rename(ID_camp = ID_camp_co2)%>%
  mutate(ID_camp = as.numeric(as.character(ID_camp)))%>%
  group_by(ID_camp, placette)%>%
  summarise(timestamp=min(ts_ch4, na.rm=T), CH4=mean(CH4, na.rm=T))%>%
  mutate(timestamp=as.POSIXct(round(timestamp, "hours")))

# Récupération du CO2
dfER <- svNetFlux %>%
  filter(type == "ER")%>%
  select(date, placette, netCO2F)%>%
  # select(ID_camp, date, placette, netCO2F)%>%
  rename(ER=netCO2F)

# Récupération du CO2
dfco2<- svNetFlux %>%
  filter(type == "NEE")%>%
  select(date, placette, netCO2F)%>%
  left_join(., dfER)%>%
  mutate(GPP = netCO2F+ER)%>%
  # select(ID_camp, date, placette, netCO2F)%>%
  rename(ENE=netCO2F)

# Récupération du niveau de la nappe
dfctrl <- svCtrlFact%>%
  select(ID_camp, date, placette, WTL)

# Récupération du niveau des température
dfT <- svTemperature%>%
  select(ID_camp, placette, Tair, T5, T10, T20, T30, T40, T50, T60, T70, T80, T90, T100)%>%
  mutate(placette = as.character(placette))

# Récupération de la végétation
dfveg <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/svIVcov.csv") %>%
  select(ID_camp, placette, IVcov, A, H, M)%>%
  mutate(placette = as.character(placette))

# Récupération données station
cT <- wrLGT %>%
  select(timestamp, Ta, Ts_1, Ts_2, Ts_3, Ts_4)%>%
  filter(timestamp >= as.POSIXct("01/01/2013", format = "%d/%m/%Y"))%>%
  rename(TairS=Ta, T5S=Ts_1, T10S=Ts_2, T20S=Ts_3, T40S=Ts_4)%>%
  mutate(hour = cut(timestamp, breaks="hours"))%>% # daily mean
  select(-timestamp)%>%
  group_by(hour)%>%
  summarise_each(funs(mean))%>%
  mutate(timestamp = as.POSIXct(hour, format="%Y-%m-%d %H:%M:%S"))%>%
  select(-hour)#%>%
  # mutate(timestamp = as.factor(timestamp))

# Fusion de toutes les données
dfges <- dfctrl %>%
  left_join(., dfco2)%>%
  left_join(., dfT)%>%
  left_join(., dfveg)%>%
  left_join(., vsch4)%>%
  left_join(., cT, by=c("timestamp"))#%>%
  # filter(!is.na(CH4))#
  
# Moyenne par campagne
dfgesm <- dfges %>%
  group_by(ID_camp)%>%
  summarise(
            GPP_sd = sd(GPP, na.rm=T),
            GPP = mean(GPP, na.rm=T),
            ER_sd = sd(ER, na.rm=T),
            ER = mean(ER, na.rm=T),
            ENE_sd = sd(ENE, na.rm=T),
            ENE = mean(ENE, na.rm=T),
            CH4_sd = sd(CH4, na.rm=T),
            CH4 = mean(CH4, na.rm=T),
            date=min(date, na.rm=T),
            timestamp=mean(timestamp, na.rm=T),
            Tair=mean(Tair, na.rm=T),
            TairS=mean(TairS, na.rm=T),
            T5S=mean(T5S, na.rm=T),
            T10S=mean(T10S, na.rm=T),
            T20S=mean(T20S, na.rm=T),
            T40S=mean(T40S, na.rm=T),
            T5=mean(T5, na.rm=T),
            T10=mean(T10, na.rm=T),
            T20=mean(T20, na.rm=T),
            T30=mean(T30, na.rm=T),
            T40=mean(T40, na.rm=T),
            T50=mean(T50, na.rm=T),
            T60=mean(T60, na.rm=T),
            T70=mean(T70, na.rm=T),
            T80=mean(T80, na.rm=T),
            T90=mean(T90, na.rm=T),
            IVcov=mean(IVcov, na.rm=T),
            A=mean(A, na.rm=T),
            H=mean(H, na.rm=T),
            M=mean(M, na.rm=T),
            WTL=mean(WTL, na.rm=T)
            )%>%
  mutate(date = as.POSIXct(date, format="%Y-%m-%d"))
#########################################################
# Ajout Tair station

```

# Calib

```{r}
# IVcov mdl exp
dmdl_IVcov <- dfgesm %>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=IVcov)%>%
  select(Y, X, WTL, Tair, A, H, M, T20, T30, T40, T50, T80)
mdl_IVcov_lin <- mdl_lin(dmdl_IVcov)
par_IVcov_lin <- mdl_param(dmdl_IVcov, mdl_IVcov_lin)

mdl_IVcov_exp <- mdl_exp(dmdl_IVcov, strt=list(a=.1, b=.2))
par_IVcov_exp <- mdl_param(dmdl_IVcov, mdl_IVcov_exp)

# T40 mdl exp
dmdl_T40 <- dfgesm %>%
  filter(!is.na(CH4))%>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=T40)%>%
  select(Y, X, WTL, Tair, A, IVcov, M)
mdl_T40_lin <- mdl_lin(dmdl_T40)
par_T40_lin <- mdl_param(dmdl_T40, mdl_T40_lin)

mdl_T40_exp <- mdl_exp(dmdl_T40, strt=list(a=.1, b=0.01))
par_T40_exp <- mdl_param(dmdl_T40, mdl_T40_exp)

# T80 mdl exp
dmdl_T80 <- dfgesm %>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=T80)%>%
  select(Y, X, WTL, Tair, A, IVcov, M)
mdl_T80_lin <- mdl_lin(dmdl_T80)
par_T80_lin <- mdl_param(dmdl_T80, mdl_T80_lin)

mdl_T80_exp <- mdl_exp(dmdl_T80, strt=list(a=.1, b=0.01))
par_T80_exp <- mdl_param(dmdl_T80, mdl_T80_exp)

# H mdl exp
dmdl_H <- dfgesm %>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=H)%>%
  select(Y, X, WTL, Tair, A, IVcov, M, T20, T30, T40, T50, T80)
mdl_H_lin <- mdl_lin(dmdl_H)
par_H_lin <- mdl_param(dmdl_H, mdl_H_lin)

mdl_H_exp <- mdl_exp(dmdl_H, strt=list(a=.1, b=0.01))
par_H_exp <- mdl_param(dmdl_H, mdl_H_exp)

# A mdl exp
dmdl_A <- dfgesm %>%
  filter(!is.na(CH4))%>%
  rename(Y=CH4, X=A)%>%
  select(Y, X, WTL, Tair, M, H, IVcov)
mdl_A_lin <- mdl_lin(dmdl_A)
par_A_lin <- mdl_param(dmdl_A, mdl_A_lin)

mdl_A_exp <- mdl_exp(dmdl_A, strt=list(a=.1, b=0.01))
par_A_exp <- mdl_param(dmdl_A, mdl_A_exp)

# Resume
mdlls <- c("IVcov_lin", "IVcov_exp", "H_lin", "H_exp", "A_lin","A_exp", "T40_exp", "T80_exp")

par <- c(par_IVcov_lin, par_IVcov_exp,
         par_H_lin, par_H_exp,
         par_A_lin, par_A_lin,
         par_T40_exp, par_T80_exp)
mdlpar <- data.frame(matrix(unlist(par), nrow=length(mdlls), byrow=T))
colnames(mdlpar) <- c("a", "b", "c", "a_se", "b_se", "c_se", "R2", "R2a", "rmse", "nrmse", "aic", "bic")

res <- data.frame(mdl=mdlls)
res <- cbind(res, mdlpar)
result <- res
result[,-1] <- round(result[,-1],2) # round sauf 1re col

arrange(result, nrmse)
```

# Val
```{r load_mdl_par}
CH4par <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/CH4_mdlpar.csv")

lCH4par <- CH4par %>%
  gather(par, value, 2:4)%>%
  do(na.omit(.))%>%
  arrange(mdl, par)
```


```{r}
get_pCH4 <- function(name="H_exp", df=df){
  parCH4 <- lCH4par %>%
    filter(mdl == name)
  # Vérif nom mdl
  if(NROW(parCH4) == 0){
    cat("souci avec mdl, pas de paramètres trouvés_n")
  }
  
  # retrieve par
  a <- parCH4$val[1]
  b <- parCH4$val[2]
  
  # lin or exp
  p <- strsplit(name, "_")[[1]][1]
  m <- strsplit(name, "_")[[1]][2]
  
  dft <- df[,c(p)]
  
  #Savoir si 1 ou plusieur variable création df ER, X1, X2
  if(m == "exp"){
    pCH4 <- a*exp(b*dft[,1])
  }else{
    pCH4 <- (a + b*dft[,1])
  }
  # return(pCH4)
  return(as.vector(pCH4[,1]))
}


mdl_indic <- function(Y, pY, mdl){
  mdl <- unique(mdl)
  if(grepl("_", mdl)){
    p <- 2
  }else{ p <- 1}
  # R2
  devmean <- Y-(mean(Y, na.rm=TRUE)) # deviation à la moyenne
  SSres <-sum((Y-pY)^2) # Total sum of squares
  SStot <- sum(devmean^2) # Residual sum of squares
  # 2 way to calculate
  R2 <- (SStot-SSres)/SStot 
  # R2 <- 1 - SSres/SStot
  # Adjusted R2
  N <- NROW(devmean) # sample size
  # p <- 1 # number of predictors
  R2a <- 1-((1-R2)*(N-1))/(N-p-1)
  # RMSE
  rmse_mdl <- sqrt(mean((pY-Y)^2,na.rm=TRUE))
  nrmse_mdl <- 100*rmse_mdl/mean(Y,na.rm=TRUE)
  # Collect usefull param
  df <- data.frame(R2=R2,
                   aR2=R2a,
                   rmse=rmse_mdl,
                   nrmse=nrmse_mdl)
  return(df)
}

```


```{r load_data}
# Données flux
dfch4 <- cdCH4 %>%
  filter(treatment == "C")%>%
  select(campaign, treatment, localisation, replicate, ch4)%>%
  group_by(campaign,  localisation)%>%
  # group_by(campaign, localisation, replicate)%>%
  summarise(ch4 = (mean(ch4, na.rm=T)))

# Données végétation (a mettre dans pkg carbiodiv)
dfveg <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/cdIVcov.csv")%>%
  filter(campaign > 1)%>%
  filter(treatment == "C")%>%
  # select(campaign, localisation, IVcov)%>%
  mutate(replicate=as.factor(replicate))%>%
  group_by(campaign, localisation)%>%
  # group_by(campaign, localisation, replicate)%>%
  summarise(IVcov = mean(IVcov, na.rm=T), H = mean(H, na.rm=T))

# Création data pour campagne 1
crea <- dfveg %>%
  ungroup()%>%
  filter(campaign == 2)%>%
  mutate(campaign = 1)
dfveg <- rbind(crea, dfveg)


# Données météo
dfwr1 <- wrLGT %>% # Données station
  select(timestamp, Ta, Ts_1)%>%
  rename(Tair=Ta, T5=Ts_1)%>%
  filter(timestamp >= as.POSIXct("01/01/2014", format = "%d/%m/%Y"))
dfwr2 <- cdNetFlux %>% # Tableau type données carbiodiv
  select(timestamp, campaign, cycle_no, treatment, localisation, replicate)%>%
  mutate(timestamp = as.POSIXct(round(timestamp, "hours")))
dfwr <- left_join(dfwr2, dfwr1)%>% # Fusion des 2
  # group_by(campaign, cycle_no, localisation)%>%
  group_by(campaign, localisation)%>%
  # group_by(campaign, localisation, replicate)%>%
  summarise(Tair = mean(Tair, na.rm=T), T5 = mean(T5, na.rm=T))
  
df <- dfch4 %>%
  left_join(., dfveg, by=c("campaign", "localisation"))%>%
#   left_join(., dfwr)%>%
#   ungroup()%>%
  filter(campaign > 1)
```

```{r, compil_data}
dfFLUX <- df %>%
  select(ch4, localisation, IVcov, H)#%>%
  # mutate(ch4 = ch4*1000) # calib faite en nmol
# Liste des modèles à tester
CH4_par <- c("H_exp", "IVcov_lin", "IVcov_exp")

# Calcul prediction CH4
predCH4 <- data.frame()

for (j in CH4_par){
    pCH4 <- get_pCH4(j, dfFLUX)
    tpCH4 <- data.frame(CH4=dfFLUX$ch4, mdl=j, loc=dfFLUX$localisation, pCH4=pCH4)
    predCH4 <- rbind(predCH4,tpCH4)
}
```

```{r}
# Tableau resultats modèles NEE
resCH4 <- predCH4 %>%
  do(na.omit(.))%>%
  group_by(mdl)%>%
  do(mdl_indic(.$CH4, .$pCH4, mdl=.$mdl))%>%
  ungroup()%>%
  arrange(desc(aR2))
```












# Figures
```{r, fig.height=8}
# labpar_1 <- format(par_IVcov_exp,  digits=2, nsmall=2)
# 
# labIV <- paste(
#   "y = ", labpar_1$a, " * exp(", labpar_1$b, "* IV)",
#   "\nR² = ", labpar_1$aR2, 
#   "\nRMSE = ", labpar_1$rmse, 
#   "\nNRMSE = ", labpar_1$nrmse, " %", sep="")
# Calib
labIV <- paste(
  # "y = ", format(par_IVcov_exp$a, digits = 3), "*exp(", format(par_IVcov_exp$b, digits = 3), "*Tair)",
  "\nR² = ", format(par_IVcov_exp$aR2, digits = 2),
  "\nRMSE = ", format(par_IVcov_exp$rmse, digits = 3),
  "\nNRMSE = ", format(par_IVcov_exp$nrmse, digits = 1), " %", sep="")

# Val
tt <- filter(resCH4, mdl=="IVcov_exp")
labIV_val <- paste(
  # "y = ", format(par_1$a, digits = 3), "*exp(", format(par_1$b, digits = 3), "*Tair)",
  "\nR² = ", format(tt$aR2, digits = 2),
  "\nRMSE = ", format(tt$rmse, digits = 3),
  "\nNRMSE = ", format(tt$nrmse, digits = 1), " %", sep="")

cairo_pdf(file.path("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/carbonbalance/ecosyst/figures", "mdl_CH4_IV.pdf"), width=9, height=6)
par(mfrow=c(2,3),mar=c(4,4.5,.5,.5))
# haut G
plot(Y~predict(mdl_IVcov_exp), 
     # ylim=c(0,200),xlim=c(0,200),
     xlab="", ylab="", data=dmdl_IVcov, cex=1.5, cex.axis=1.3)
title(xlab=expression(paste("CH"[4]," modélisée (", mu, mol,m^-2,s^-1,")", sep="")), line=2.5, cex.lab=1.2)
title(ylab=expression(paste("CH"[4]," mesurée (", mu, mol,m^-2,s^-1,")", sep="")), line=2, cex.lab=1.2)
abline(a=0, b=1, col="grey", lty=2)
text(.16,.17, "1:1", srt=45, col="grey")
text(x=.005, y=.17, labels=labIV, adj=0)
text(x=.17, y=0.02, labels="a", adj=0, cex=2)

# haut M
plot(resid(mdl_IVcov_exp)~predict(mdl_IVcov_exp), 
     xlab="", ylab="", ylim=c(-0.06, 0.06), cex=1.5, cex.axis=1.3)
abline(h=0, lty="dashed", col="grey")
# abline(h=0.04, lty="dotted")
# abline(h=-0.04, lty="dotted")
title(xlab=expression(paste("Valeurs prédites (", mu, mol,m^-2,s^-1,")", sep="")), line=2.5, cex.lab=1.2)
title(ylab=expression(paste("Résidus (", mu, mol,m^-2,s^-1,")", sep="")), line=2, cex.lab=1.2)
text(x=.17, y=-0.052, labels="b", adj=0, cex=2)
# Haut D
dat <- filter(predCH4, mdl == "IVcov_exp")
plot(CH4~pCH4,
     data=dat,
     xlim=c(0,.1), ylim=c(0,.1),
     xlab="", ylab="", cex=1.5, cex.axis=1.3)
title(xlab=expression(paste("CH"[4], " modélisée (", mu, mol,m^-2,s^-1,")", sep="")), line=2.5, cex.lab=1.2)
title(ylab=expression(paste("CH"[4], " mesurée (", mu, mol,m^-2,s^-1,")", sep="")), line=2, cex.lab=1.2)
abline(a=0, b=1, col="grey", lty=2)
text(x=.001, y=.095, labels=labIV_val, adj=0)
text(0.09,0.095, "1:1", srt=45, col="grey")
text(x=.092, y=0.005, labels="c", adj=0, cex=2)

## bas gauche
plot(resid(mdl_IVcov_exp)~dmdl_IVcov$WTL, xlab="", ylab="", ylim=c(-0.06, 0.06), cex=1.5, cex.axis=1.3) 
title(xlab="Niveau de la nappe (cm)", line=2.5, cex.lab=1.2)
title(ylab=expression(paste("Résidus (", mu, mol,m^-2,s^-1,")", sep="")), line=2, cex.lab=1.2)
text(x=17.6, y=-0.052, labels="d", adj=0, cex=2)
## bas mil
plot(resid(mdl_IVcov_exp)~dmdl_IVcov$T20, xlab="", ylab="", ylim=c(-0.06, 0.06), cex=1.5, cex.axis=1.3) 
title(xlab="Température du sol à -20 cm (°C)", line=2.5, cex.lab=1.2)
title(ylab=expression(paste("Résidus (", mu, mol,m^-2,s^-1,")", sep="")), line=2, cex.lab=1.2)
text(x=17.5, y=-0.052, labels="e", adj=0, cex=2)
## bas droit
plot(resid(mdl_IVcov_exp)~dmdl_IVcov$T40, xlab="", ylab="", ylim=c(-0.06, 0.06), cex=1.5, cex.axis=1.3) 
title(xlab="Température du sol à -40 cm (°C)", line=2.5, cex.lab=1.2)
title(ylab=expression(paste("Résidus (", mu, mol,m^-2,s^-1,")", sep="")), line=2, cex.lab=1.2)
text(x=16.5, y=-0.052, labels="f", adj=0, cex=2)
par(mfrow=c(1,1))
dev.off()


cairo_pdf(file.path("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/carbonbalance/ecosyst/figures", "mdl_CH4_IV_cal.pdf"), width=5, height=5)
plot(Y~predict(mdl_IVcov_exp), 
     # ylim=c(0,200),xlim=c(0,200),
     xlab="", ylab="", data=dmdl_IVcov, cex=1.5, cex.axis=1.3)
title(xlab=expression(paste("CH"[4]," modélisée (", mu, mol,m^-2,s^-1,")", sep="")), line=2.5, cex.lab=1.2)
title(ylab=expression(paste("CH"[4]," mesurée (", mu, mol,m^-2,s^-1,")", sep="")), line=2, cex.lab=1.2)
abline(a=0, b=1, col="grey", lty=2)
text(.16,.17, "1:1", srt=45, col="grey")
text(x=.005, y=.17, labels=labIV, adj=0)
# text(x=.17, y=0.02, labels="a", adj=0, cex=2)
dev.off()
```

