# Obj ---------------------------------------------------------------------
# This script gather all fluxes and environmental data.
# These are elaborate data that have been treated (scripts are saved in /src/data_trtmt): 
# The vegetation data are treated by getClean_veg.R
# The CO2 data are treated by getClean_co2.R
# The CH4 data are treated by getClean_ch4.R

# Output : 
# This script output 2 files :
# - cl_fluxesFC.csv (data per measurement point)
# - cl_fluxesFC_avg.csv (data averaged by campaign)


# Setup -------------------------------------------------------------------
rm(list=ls(all=TRUE)) # Clean start
library(laguettevarspa)
library(snoweather)
library(dplyr)
library(tidyr)

# Folder to save the treatements ------------------------------------------
outpath <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed"

## Flux CO2
dfco2 <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/cl_CO2.csv") %>%
  spread(F_type, flux)%>%
  select(ID_camp, date, placette, ER, GPP, NEE)%>%
  mutate(placette = as.character(placette))
  
## Flux CH4
dfch4 <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/cl_CH4.csv") %>%
  mutate(timestamp=as.POSIXct(as.character(timestamp)))%>%
  mutate(timestamp=as.POSIXct(round(timestamp, "hours")))%>%
  select(ID_camp, timestamp, placette, CH4)%>%
  mutate(placette = as.character(placette))

# Retrieve environmental variables
dfctrl <- svCtrlFact %>%
  select(ID_camp, placette, WTL, RH_m, NPOC, PAR_Deb, PAR_Fin)%>%
  gather(type, val, 6:7)%>% # PAR mean calculation
  group_by(ID_camp, placette)%>%
  summarise(WTL=mean(WTL, na.rm=T), PAR=mean(val, na.rm=T), RH_m=mean(RH_m, na.rm=T), NPOC=mean(NPOC, na.rm=T))%>%
  ungroup()%>%
  mutate(placette = as.character(placette))

# Retrieve temperature data
dfT <- svTemperature%>%
  select(ID_camp, placette, Tair, T5, T10, T20, T30, T40, T50, T60, T70, T80, T90, T100)%>%
  mutate(placette = as.character(placette))

# Retrieve vegetation data (generated by getClean_veg.R)
dfveg <- read.csv("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/data/processed/svIVcov.csv") %>%
  select(ID_camp, placette, IVcov, A, H, M, IVcov_area)%>%
  mutate(placette = as.character(placette))

# Retrieve weather station data
cT <- wrLGT %>%
  select(timestamp, Ta, Ts_1, Ts_2, Ts_3, Ts_4)%>%
  filter(timestamp >= as.POSIXct("01/01/2013", format = "%d/%m/%Y"))%>%
  rename(TairS=Ta, T5S=Ts_1, T10S=Ts_2, T20S=Ts_3, T40S=Ts_4)%>%
  mutate(hour = cut(timestamp, breaks="hours"))%>% # daily mean
  select(-timestamp)%>%
  group_by(hour)%>%
  summarise_each(funs(mean))%>%
  mutate(timestamp = as.POSIXct(hour, format="%Y-%m-%d %H:%M:%S"))%>%
  select(-hour)

# Merge all data
df <- dfctrl %>%
  left_join(., dfco2)%>%
  left_join(., dfT)%>%
  left_join(., dfveg)%>%
  left_join(., dfch4)%>%
  left_join(., cT, by=c("timestamp"))#%>%
# filter(!is.na(CH4))#


# Averaging by campaign ---------------------------------------------------
dfm <- df %>%
  mutate(date=as.POSIXct(as.character(date)))%>%
  group_by(ID_camp)%>%
  summarise(
    GPP_sd = sd(GPP, na.rm=T),
    GPP = mean(GPP, na.rm=T),
    ER_sd = sd(ER, na.rm=T),
    ER = mean(ER, na.rm=T),
    NEE_sd = sd(NEE, na.rm=T),
    NEE = mean(NEE, na.rm=T),
    CH4_sd = sd(CH4, na.rm=T),
    CH4 = mean(CH4, na.rm=T),
    PAR = mean(PAR, na.rm=T),
    date=min(date, na.rm=T),
    timestamp=mean(timestamp, na.rm=T),
    Tair=mean(Tair, na.rm=T),
    TairS=mean(TairS, na.rm=T),
    T5S=mean(T5S, na.rm=T),
    T10S=mean(T10S, na.rm=T),
    T20S=mean(T20S, na.rm=T),
    T40S=mean(T40S, na.rm=T),
    T5=mean(T5, na.rm=T),
    T10=mean(T10, na.rm=T),
    T20=mean(T20, na.rm=T),
    T30=mean(T30, na.rm=T),
    T40=mean(T40, na.rm=T),
    T50=mean(T50, na.rm=T),
    T60=mean(T60, na.rm=T),
    T70=mean(T70, na.rm=T),
    T80=mean(T80, na.rm=T),
    T90=mean(T90, na.rm=T),
    T100=mean(T100, na.rm=T),
    IVcov=mean(IVcov, na.rm=T),
    IVcov_area=mean(IVcov_area, na.rm=T),
    A=mean(A, na.rm=T),
    H=mean(H, na.rm=T),
    M=mean(M, na.rm=T),
    RH_m=mean(RH_m, na.rm=T),
    NPOC=mean(NPOC, na.rm=T),
    WTL=mean(WTL, na.rm=T)
  )

# Save treatement in file -------------------------------------------------
write.csv(df, file.path(outpath, "cl_fluxesFC.csv"), quote=F, row.names=F)
write.csv(dfm, file.path(outpath, "cl_fluxesFC_avg.csv"), quote=F, row.names=F)
