---
title: "Échange Net de l'Écosystème : model"
author: "Benoît D'ANGELO"
date: "07/04/2015"
output:
  html_document:
    includes:
      in_header: ../../in_header.html
    theme: flatly
    toc: yes
    toc_depth: 2
---

<h3><a href="../CB_toc.html"> Carbon balance </a></h3>

***

```{r setup, echo=FALSE, message=FALSE}
rm(list=ls(all=TRUE))

library(laguettevarspa)
library(snoweather)
library(bdphdtoolbox)

# library(data.table)
library(dplyr)
library(tidyr)
library(ggplot2)

savpth <- "/home/dangelo/Documents/4.Sci.penceStuff/2.Projects/2013_spaVar_LG/graphs/carbonbalance"

knitr::opts_chunk$set(fig.width=12,fig.height=8,echo=FALSE, warning=FALSE,message=FALSE)
options(width = 100)
```


```{r load data}
# Fichier VS
df_ER <- svNetFlux %>%
  filter(type == "ER", date >= as.Date("2014-01-01"))%>%
  select(timestamp, ID_camp, placette, R2, pvalue, mtime, netCO2F)%>%
  left_join(., svTemperature, by=c("ID_camp", "placette")) %>%
  left_join(., svCtrlFact, by=c("ID_camp", "placette")) %>%
  select(ID_camp, placette, netCO2F, T25)%>%
  mutate(predER = 0.2495762*exp(0.192905*T25))%>%
  rename(ER=netCO2F)%>%
  filter(ER > 0) # remove value below 0


# Tair param (June)
# a <- 13.66704
# b <- 40.98826
# c <- 24.4913

# T15 param (June)
a <- 12.96248
b <- 19.05099
c <- -8.051285

# T25 param (June)
# a <- 12.62158
# b <- 17.84691
# c <- 6.917579

# Fichier VS
df_tER <- svNetFlux %>%
  filter(type == "ER", date >= as.Date("2014-01-01"))%>%
  select(ID_camp, placette, netCO2F, timestamp)%>%
  rename(ER=netCO2F, ER_ts=timestamp)%>%
  mutate(ER_ts=as.POSIXct(ER_ts))

df_tNEE <- svNetFlux %>%
  filter(type == "NEE", date >= as.Date("2014-01-01")) %>%
  select(ID_camp, placette, netCO2F, timestamp)%>%
  rename(NEE=netCO2F, NEE_ts=timestamp)%>%
  mutate(NEE_ts=as.POSIXct(NEE_ts))

df_GPP <- inner_join(df_tER, df_tNEE)%>%
  mutate(netCO2F=NEE+ER) %>%
  group_by(ID_camp, placette)%>%
  mutate(timestamp=mean.POSIXct(c(ER_ts, NEE_ts)))%>%
  ungroup()%>%
  select(ID_camp, placette, netCO2F, timestamp)

df_GPP <- df_GPP %>%
  # filter(type == "GPP")%>%
  # select(timestamp, ID_camp, placette, netCO2F)%>%
  left_join(., svTemperature, by=c("ID_camp", "placette")) %>%
  left_join(., svCtrlFact, by=c("ID_camp", "placette")) %>%
  group_by(timestamp)%>%
  mutate(PAR=mean(c(PAR_Deb, PAR_Fin, na.rm=TRUE)))%>%
  ungroup()%>%
  select(ID_camp, placette, netCO2F, Tair, T15, PAR)%>%
  mutate(predGPPsat = a * exp(-((T15-b)/c)^2))%>%
  # mutate(predGPPsat = a * exp(-((Tair-b)/c)^2))%>%
  rename(GPP=netCO2F)
  # filter(netCO2F > 0) # remove value below 0

df_NEE <- svNetFlux %>%
  filter(type == "NEE") %>%
  select(ID_camp, placette, netCO2F, timestamp)%>%
  rename(NEE=netCO2F)

df <- inner_join(df_ER, df_GPP)%>%
  inner_join(.,df_NEE)%>%
  do(na.omit(.))%>%
  arrange(placette)


# Comme Borto mais attention plutot prendre Tair station ?
mnls <- nls(NEE ~ (a*PAR*predGPPsat/(predGPPsat+PAR*a)-ER) , data=df, start=list(a=0.005))
summary(mnls)

df$resi <- resid(mnls)
df$predNEE <- predict(mnls)
```

## ENE representation


```{r, fig.width=8}

plot(df$NEE~df$predNEE, xlim=c(-5,10), ylim=c(-5,10))
t <- lm(df$NEE~df$predNEE)
abline(a = 0, b = 1)

# rmse <- sqrt((sum(df$NEE-df$predNEE)^2)/NROW(df))
rmse <- sqrt(mean((df$predNEE-df$NEE)^2,na.rm=TRUE))
rmse
```

A voir : 

- Comment estimer la qualité de la régression

- Comment justifier l'utilisation de la fonction de June pour GPPsat



```{r, fig.width=8}

rmse <- c()
for (i in unique(df$placette)){
  temp <- df %>%
    select(ID_camp, placette, NEE, predNEE)%>%
    filter(placette == i)
  trmse <- sqrt(mean((temp$predNEE-temp$NEE)^2,na.rm=TRUE))
  rmse <- c(rmse, trmse)

  plot(temp$NEE~temp$predNEE, xlim=c(-5,10), ylim=c(-5,10), main=paste(i, trmse))
  abline(a = 0, b = 1)
  # t <- lm(df$NEE~df$predNEE)
}
rmse
dfrmse <- data.frame(placette=unique(df$placette), rmse=rmse)
arrange(dfrmse, rmse)
# rmse <- sqrt((sum(df$NEE-df$predNEE)^2)/NROW(df))
```
