Evolution par placette
========================================================


### <a href="../TOC_VS.html"> Retour 1re page </a>

***

```{r loadenv, eval=TRUE, echo=FALSE, message=FALSE}

loadenv <- function(){
   source("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/src/load.R")
#   source("/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_JourNuit/src/3_functions/reportFn.R")
  set_alias(w = "fig.width", h = "fig.height") 
  output_pth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs"
#   cat("loadenv : done \n")
  }

# Calls
loadenv()
dfCO2 <- ld_CO2()
dfPT<- ld_PT(long=F)
dfTE<- ld_TE()

df <- join(join(dfCO2, dfPT), dfTE)
df$ID_camp <- as.factor(df$ID_camp)
df$ReAbs <- abs(df$Re)
df$date <- as.Date(df$date)

```


## Évolution de la respiration au cours du temps

La ligne tiretée rouge correspond à la moyenne de l'ensembles des points

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8, dpi=100}

summa <- function(x) {
#   mReAbs = mean(x$ReAbs, na.rm = TRUE)
  c(mReAbs = mean(x$ReAbs, na.rm = TRUE),
  seReAbs = (sd(x$ReAbs, na.rm = TRUE)/sqrt(NROW(x))))
}

lsdate <- get_dateList(type="all")
colnames(lsdate) <- c("date", "ID_camp")
df$date <- NULL
df <- join(df, lsdate)


mdf <- ddply(df, .(date), summa) 

mdf$CI95 <- (95/2)*mdf$seReAbs

ggplot(mdf, aes(x=date, y=mReAbs, group=1))+
  geom_line() +
#   geom_line(data=mdf, aes(x=date, y=(mReAbs+CI95), color = "red"), linetype="dashed") +
#   geom_line(data=mdf, aes(x=date, y=(mReAbs-CI95), color = "red"), linetype="dashed") +
  geom_line(data=mdf, aes(x=date, y=(mReAbs+seReAbs), color = "red"), linetype="dashed") +
  geom_line(data=mdf, aes(x=date, y=(mReAbs-seReAbs), color = "red"), linetype="dashed") +
  labs(title="Évolution de la respiration de l'écosystème en fonction du temps \n  (moyenne des 20 placettes)", x="temps", y="Re (µmol.m⁻².s⁻²)")+
  theme_bw()+
  theme(legend.position="none")


# mdf <- join(df[,c("placette", "date")], mdf)

ggplot(df, aes(x=date, y=ReAbs))+
  geom_line(data=mdf, aes(x=date, y=mReAbs, color = "red"), linetype = "dashed") +
#   geom_line(data=mdf, aes(x=date, y=(mReAbs+seReAbs), color = "red"), linetype="dashed") +
#   geom_line(data=mdf, aes(x=date, y=(mReAbs-seReAbs), color = "red"), linetype="dashed") +
  geom_line() +
  labs(title=("Évolution de la respiration de l'écosystème en fonction du temps"))+
  facet_wrap(~placette)+
  theme_bw()

```


## Évolution de l'échange net de l'écosystème (NEE) au cours du temps

La ligne tiretée rouge correspond à la moyenne de l'ensembles des points

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8, dpi=100}

summa <- function(x) {
#   mReAbs = mean(x$ReAbs, na.rm = TRUE)
  c(mNEP = mean(x$NEP, na.rm = TRUE),
  seNEP= (sd(x$NEP, na.rm = TRUE)/sqrt(NROW(x))))
}

mdf <- ddply(df, .(date), summa) 

# mdf <- join(df[,c("placette", "date")], mdf)

ggplot(df, aes(x=date, y=NEP))+
  geom_line(data=mdf, aes(x=date, y=mNEP, color = "red"), linetype = "dashed") +
  geom_line() +
  labs(title=("Évolution de la respiration de l'écosystème en fonction du temps"))+
  facet_wrap(~placette)+
  theme_bw()

```

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8, dpi=100}

summa <- function(x) {
#   mReAbs = mean(x$ReAbs, na.rm = TRUE)
  c(mWT = mean(x$WT, na.rm = TRUE),
  seWT= (sd(x$WT, na.rm = TRUE)/sqrt(NROW(x))))
}

mdf <- ddply(df, .(date), summa) 

# mdf <- join(df[,c("placette", "date")], mdf)

ggplot(df, aes(x=date, y=WT))+
  geom_line(data=mdf, aes(x=date, y=mWT, color = "red"), linetype = "dashed") +
  geom_line() +
  labs(title=("Évolution de la respiration de l'écosystème en fonction du temps"))+
  facet_wrap(~placette)+
  theme_bw()

```