---
title: "Molinia"
author: "Benoît D'ANGELO"
date: "02/03/2015"
output:
  html_document:
    fig_height: 7
    fig_width: 9
    includes:
      in_header: ../../in_header.html
    theme: flatly
    toc: yes
---
<h3><a href="../vis_toc.html"> Visualisation </a></h3>
  
***

```{r load_env, eval=TRUE, echo=FALSE, message=FALSE}
rm(list=ls(all=TRUE))
library(laguettevarspa)
library(ggplot2)
library(dplyr)
library(tidyr)

source("../../../src/report/vis_veg_plot.R")
source("../../../src/functions/trt_veg.R")

savpth <- "../../../graphs/visualisation"
```


```{r load_data, eval=TRUE, echo=FALSE, message=FALSE}
df <- svVegetation %>%
  filter(specie %in% c("molinia")) %>%
  filter(!is.na(number))%>%
  mutate(cover=as.character(cover))%>%
  mutate(cover = ifelse(cover == "<5", "0", cover))%>%
  mutate(cover = ifelse(cover == "9999", NA, cover))%>%
  mutate(cover = as.numeric(cover))%>%
  mutate(height_tot = height_m*number)
  

# df$cover <- ifelse(df$cover == "<5", "0", df$cover)

cover <- trt_veg()%>%
  filter(specie %in% c("molinia"))
```

## Evolution of the molinia's number

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8}
# A partir du 19/3/2014 les molinies et erio sont comptés
# ggplot(df, aes(x=date, y=number, color = as.factor(ID_camp)))+
veg_evol(df, "number")
ggsave("molin_N.pdf", path=savpth)
```


## Evolution of the molinia's mean height

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8}
veg_evol(df, "height")
ggsave("molin_height.pdf", path=savpth)
```

## Relationship between the average height and the number of molinia

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8}
ggplot(df, aes(x=number, y=height_m))+
  geom_point(size = 4, shape=21)+
  facet_wrap(~placette)+
  theme_bw()
ggsave("molin_N_height.pdf", path=savpth)
```


## Molinia cover

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8}
veg_cover(cover)
ggsave("molin_cover.pdf", path=savpth)
```


## Reconstruction du nombre de molinie à partir du recouvrement

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8}
ggplot(df, aes(x=cover, y=number))+
  geom_point(size = 4, shape=21)+
  geom_smooth(method="lm", se=F)+
  # facet_wrap(~placette)+
  theme_bw()

m <- lm(df$number~df$cover)
summary(m)


# ggsave("molin_cover.pdf", path=savpth)
```

### model normality and leverage

```{r , eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE, w=12, h=8}
par(mfrow=c(2,2))
hist(resid(m)) # normality
plot(m, which=2) # normality
plot(m, which=4) # leverage
plot(m, which=5) # leverage
par(mfrow=c(1,1))
```