---
title: "Physico-chemical properties"
author: "Benoît D'ANGELO"
date: "23/02/2015"
output:
  html_document:
    includes:
      in_header: ../../in_header.html
    theme: flatly
---
### <a href="../vis_toc.html"> Visualisation </a>

***
```{r, echo=FALSE, message=FALSE}
rm(list=ls())
library(laguettevarspa)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)

library(grid)
library(gridExtra)

savpth <- "/home/dangelo/Documents/4.ScienceStuff/2.Projects/2013_spaVar_LG/graphs/visualisation"

```


```{r load_dat, echo=FALSE}
# données par placette
df <- svCtrlFact%>%
  select(ID_camp, placette, date, pH, pH_localisation, Cond, Cond_localisation, NPOC)%>%
  mutate(Cond = ifelse(Cond <= 150, Cond, NA))%>%
  # filter(Cond <= 150) %>%
  separate(date, c("year","month", "day"),remove = F)

# moyenne de l'ensemble des placettes
dfm <- df %>%
  group_by(ID_camp)%>%
  summarise(date=min(date),
            year=unique(year),
            cond_sd=sd(Cond, na.rm=T),
            cond=mean(Cond, na.rm=T),
            pH_sd=sd(pH, na.rm=T),
            pH=mean(pH, na.rm=T),
            NPOC_sd=sd(NPOC, na.rm=T),
            NPOC=mean(NPOC, na.rm=T)
            )

```

## Mean pH evolution

```{r, echo=FALSE, warning=FALSE, fig.height=5, fig.width=9}
ggplot(dfm, aes(x=date, y=pH, group=year))+
  geom_point(size=3)+
  annotate("text", x=as.Date("2015-03-01"), y=5.5, label="B", size=5)+
  geom_linerange(aes(x=date, ymin=pH-pH_sd, ymax=pH+pH_sd))+
  labs(y="pH", x="")+
  scale_x_date(breaks = date_breaks("2 months"), labels = date_format("%b"))+
  theme_classic()+
  theme(plot.margin=unit(c(0,0,0,0),"mm"))
ggsave("pH_mean_evolution.pdf", path=savpth, width=7, height=3)
```

# pH for each replicate

The red line show the mean behavior

```{r, echo=FALSE, warning=FALSE, fig.height=7, fig.width=9}
ggplot(df, aes(x=date, y=pH, group=year))+
  geom_point()+
  geom_line()+
  geom_line(data=dfm, aes(x=date, y=pH, group=year), color="tomato")+
  facet_wrap(~placette)+
  theme_bw()+
  theme(axis.text.x=element_text(angle=30, hjust=1))
ggsave("pH_p7_evolution.pdf", path=savpth)
```

## Mean conductivity evolution

```{r, echo=FALSE, warning=FALSE, fig.height=5, fig.width=9}
ggplot(dfm, aes(x=date, y=cond))+
  geom_point(size=3)+
  annotate("text", x=as.Date("2015-03-01"), y=70, label="A", size=5)+
  geom_linerange(aes(x=date, ymin=cond-cond_sd, ymax=cond+cond_sd))+
  labs(y=expression(paste("Conductivité (", mu, S,m^-2,s^-1,")", sep="")), x="")+
  scale_x_date(breaks = date_breaks("2 months"), labels = date_format("%b"))+
  theme_classic()+
  theme(plot.margin=unit(c(5,0,0,0),"mm"))

ggsave("cond_mean_evolution.pdf", path=savpth, width=7, height=3)
```

# cond for each replicate

The red line show the mean behavior

```{r, echo=FALSE, warning=FALSE, fig.height=7, fig.width=9}
ggplot(df, aes(x=date, y=Cond, group=year))+
  geom_point()+
  geom_line()+
  geom_line(data=dfm, aes(x=date, y=cond, group=year), color="tomato")+
  facet_wrap(~placette)+
  theme_bw()+
  theme(axis.text.x=element_text(angle=30, hjust=1))
ggsave("cond_p7_evolution.pdf", path=savpth)
```





```{r, echo=FALSE, warning=FALSE, fig.width=9}

pcond <- ggplot(dfm, aes(x=date, y=cond))+
  geom_point(size=3)+
  annotate("text", x=as.Date("2015-03-01"), y=70, label="A", size=5)+
  geom_linerange(aes(x=date, ymin=cond-cond_sd, ymax=cond+cond_sd))+
  labs(y=expression(paste("Conductivité (", mu, S,m^-2,s^-1,")", sep="")), x="")+
  scale_x_date(breaks = date_breaks("2 months"), labels = date_format("%b"))+
  theme_classic()+
  theme(plot.margin=unit(c(5,0,0,0),"mm"))

ppH <- ggplot(dfm, aes(x=date, y=pH, group=year))+
  geom_point(size=3)+
  annotate("text", x=as.Date("2015-03-01"), y=5.5, label="B", size=5)+
  geom_linerange(aes(x=date, ymin=pH-pH_sd, ymax=pH+pH_sd))+
  labs(y="pH", x="")+
  scale_x_date(breaks = date_breaks("2 months"), labels = date_format("%b"))+
  theme_classic()+
  theme(plot.margin=unit(c(0,0,0,0),"mm"))

pDOC <- ggplot(dfm, aes(x=date, y=NPOC, group=year))+
  geom_point(size=3)+
  annotate("text", x=as.Date("2015-03-01"), y=50, label="C", size=5)+
  geom_linerange(aes(x=date, ymin=NPOC-NPOC_sd, ymax=NPOC+NPOC_sd))+
  labs(y=expression(paste("carbone organique dissout (mg",L^-1,")", sep="")), x="2013-2014")+
  scale_x_date(breaks = date_breaks("2 months"), labels = date_format("%b"))+
  theme_classic()+
  theme(plot.margin=unit(c(0,0,0,0),"mm"))
# ggsave("NPOC_mean_evolution.pdf", path=savpth, width=7, height=3)


cairo_pdf(file.path(savpth, "wtr_physicochim.pdf"), width=7, height=8.5)
grid.arrange(pcond, ppH, pDOC)
dev.off()
```

