---
title: "Water Table Level (WTL)"
author: "Benoît D'ANGELO"
date: "23/02/2015"
output:
  html_document:
    code_folding: hide
    fig_height: 5
    includes:
      in_header: ../../in_header.html
    theme: flatly
    toc: yes
    toc_depth: 2
    toc_float: yes
---
### <a href="../vis_toc.html"> Visualisation </a>

***

# Setup

## Load packages and set paths

```{r, echo=FALSE, message=FALSE}
# File name : /2013_spavar_LG/report/visualisation/controlling_factors/wtl.Rmd
rm(list=ls(all=TRUE)) # Clean start

# Homemade 
library(laguettevarspa)
# CRAN
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(rprojroot)  # allow easier relative path

# Find project root
r <- rprojroot::is_rstudio_project
root <- r$find_file()

# Folder to save graphes
savpth <- file.path(root, "graphs", "visualisation")

# Load custom color set
source(file.path(root, "src", "report", "custom_colors.R"))
source(file.path(root, "src", "report", "custom_themes.R"))
```

# WTL chronicles {.tabset}

```{r load_dat, echo=FALSE}
# Spatial variability data
## data per measurement plot
df <- svCtrlFact%>%
  select(ID_camp, placette, date, PiezoNap, PiezoVeg, WTL)%>%
  mutate(WTL = -WTL)%>%
  separate(date, c("year","month", "day"),remove = F)

## data averaged by measurement campaign
dfm <- df %>%
  group_by(ID_camp)%>%
  summarise(date=min(date),
            year=unique(year),
            WTL_sd=sd(WTL, na.rm=T),
            WTL=mean(WTL, na.rm=T)
            )

# Chronicles data
dfc <- read.csv(file.path(root, "data", "other", "niveaux_piezo_cm.csv"))%>%
  mutate(timestamp=as.POSIXct(as.character(abs), format="%Y-%m-%d %H:%M:%S"))%>%
  select(timestamp, NIV_WO, NIV_WC, NIV_DO, NIV_DC, NIV_DC_o, NIV_WC_o)%>%
  filter(timestamp >= as.POSIXct("2011-01-28 00:00:00"))%>%
  filter(timestamp <= as.POSIXct("2015-04-21 00:00:00"))

## Wide format
dfcw <- dfc %>%
  mutate(yr = strftime(timestamp, "%Y"), # deb moy jour
         mn = strftime(timestamp, "%m"),
         dy = strftime(timestamp, "%d"))%>%
  group_by(yr, mn, dy)%>%
  summarise(timestamp=median(timestamp),
            NIV_WO=mean(NIV_WO, na.rm=T),
            NIV_WC=mean(NIV_WC, na.rm=T),
            NIV_DO=mean(NIV_DO, na.rm=T),
            NIV_DC=mean(NIV_DC, na.rm=T)
            )%>%
  ungroup()%>%
  select(-yr, -mn, -dy)%>% ## Fin moy jour
  # select(-NIV_DC_o, -NIV_WC_o)%>%
  mutate(avg = rowMeans(select(., starts_with("NIV")), na.rm = TRUE))%>%
  gather("type", "val", 2:6)%>%
  do(na.omit(.))
```

## Raw chronicles

```{r}
d <- filter(dfcw, type != "avg")

ggplot(d, aes(x=timestamp, y=val))+
  geom_line()+
  facet_wrap(~type)

```

## WTL chronicles (mean of 4 auto-piezo)

```{r, fig.height=3}
d <- filter(dfcw, type == "avg")

moy <- d %>%
  separate(timestamp, c("date", "hours"), sep=" ", remove = F)%>%
  separate(timestamp, c("year", "month", "day"), sep="-", remove = T)%>%
  mutate(year = as.factor(year))%>%
  filter(year %in% c(2011, 2012, 2013, 2014))%>%
  group_by(year)%>%
  summarise(wtl_sd = round(sd(val, na.rm=T),1),
              wtl = round(mean(val, na.rm=T),1))

labt <- as.character(format(moy$wtl[1:4],digits=2))
labt <- c(labt, "annual means")
xpos <- c("2011-06-01", "2012-06-01", "2013-06-01", "2014-06-01", "2015-01-01")
xpos <- as.POSIXct(xpos)
dlab <- data.frame(xpos=xpos, labt=labt)



ggplot()+
  geom_line(aes(x=timestamp, y=val), data=d, color=lgris)+
  geom_point(aes(x=as.POSIXct(date), y=WTL), data=dfm, color=dgris, size=2)+
  geom_linerange(aes(x=as.POSIXct(date), ymin=WTL-WTL_sd, ymax=WTL+WTL_sd), data=dfm, color=dgris)+
  ylab("water table level (cm)")+
  geom_text(aes(x=xpos, y=5, label=labt), data=dlab)+
  theme_interp
ggsave("WTL_WTLc.pdf", path=savpth, width=7, height=3)

```

# Spatial variability measurements


```{r}
# Moyenne annuelle niveau
dfma <- df %>%
  group_by(year)%>%
  summarise(WTL_sd=sd(WTL, na.rm=T),
            WTL=mean(WTL, na.rm=T))

dfma
```

## Mean WTL

```{r, echo=FALSE, warning=FALSE, fig.width=9}
ggplot(dfm, aes(x=date, y=WTL, group=year))+
  geom_point(size=3)+
  geom_linerange(aes(x=date, ymin=WTL-WTL_sd, ymax=WTL+WTL_sd))+
  labs(y="niveau de la nappe (cm)", x="2013-2014")+
  scale_x_date(breaks = date_breaks("2 months"), labels = date_format("%b"))+
  theme_classic()+
  theme(plot.margin=unit(c(0,0,0,0),"mm"))
ggsave("WTL_mean_evolution.pdf", path=savpth, width=7, height=3)

ggplot(dfm, aes(x=date, y=WTL, group=year))+
  geom_point(size=3)+
  geom_linerange(aes(x=date, ymin=WTL-WTL_sd, ymax=WTL+WTL_sd))+
  annotate("text", x=as.Date("2015-02-01"), y=0, label="N=20", size=4)+
  #2013
  annotate("text", x=as.Date("2013-06-15"), y=0, label="2013", size=5)+
  annotate("text", x=as.Date("2013-12-01"), y=-8.1, label="-9,2", size=5, color=orange)+
  annotate("segment", x=as.Date("2013-03-05"), xend=as.Date("2013-12-15"), y=-9.2, yend=-9.2, linetype="dashed", size=1, color=orange)+
  #2014
  annotate("text", x=as.Date("2014-06-15"), y=0, label="2014", size=5)+
  annotate("text", x=as.Date("2015-01-01"), y=-6, label="-7,1", size=5, color=orange)+
  annotate("segment", x=as.Date("2014-03-15"), xend=as.Date("2014-12-20"), y=-7.1, yend=-7.1, linetype="dashed", size=1, color=orange)+
  labs(y="niveau de la nappe (cm)", x="")+
  scale_x_date(breaks = date_breaks("2 months"), labels = date_format("%b"))+
  theme_classic()+
  theme(plot.margin=unit(c(0,0,0,0),"mm"))
ggsave("VS_WTL_avg.pdf", path=savpth, width=7, height=3)
```

# WTL for each replicate

The red line show the mean behavior

```{r, echo=FALSE, warning=FALSE, fig.height=7, fig.width=9}
ggplot(df, aes(x=date, y=WTL, group=year))+
  geom_point(size=.8, color=orange)+
  geom_line(color=orange)+
  geom_hline(yintercept=-10, linetype="dashed", color=gris)+
  geom_line(data=dfm, aes(x=date, y=WTL, group=year), color=gris)+
  facet_wrap(~placette)+
  theme_bw()+
  theme(axis.text.x=element_text(angle=30, hjust=1),
        panel.grid.major.x = element_blank(), # DIAPO
        panel.grid.major.y = element_line(size=.05, colour="gray95"),
        panel.grid.minor = element_blank()
        )
  
ggsave("WTL_p7_evolution.pdf", path=savpth)
```
